// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        break;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI64a5RTmXeJX2omsepXFk9mYMRkBr69c',
    appId: '1:576943166736:web:9de093ba59379c326d0195',
    messagingSenderId: '576943166736',
    projectId: 'flutter-dartapp',
    authDomain: 'flutter-dartapp.firebaseapp.com',
    storageBucket: 'flutter-dartapp.appspot.com',
    measurementId: 'G-KPPSKFXZVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFb7oChuknYWMD57rmaRzCMUpSN2ksj18',
    appId: '1:576943166736:android:afddd6066d28ac666d0195',
    messagingSenderId: '576943166736',
    projectId: 'flutter-dartapp',
    storageBucket: 'flutter-dartapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBretxFeAKmvQpM1b-uMAYonpOQqokWb5g',
    appId: '1:576943166736:ios:3bc4d408bdf7b95e6d0195',
    messagingSenderId: '576943166736',
    projectId: 'flutter-dartapp',
    storageBucket: 'flutter-dartapp.appspot.com',
    androidClientId:
        '576943166736-tvniocq83o5l4sei7pn316bgroc13cbn.apps.googleusercontent.com',
    iosClientId:
        '576943166736-26qb5j9psb4l8nmqd34n3aac69guun7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.dartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBretxFeAKmvQpM1b-uMAYonpOQqokWb5g',
    appId: '1:576943166736:ios:3bc4d408bdf7b95e6d0195',
    messagingSenderId: '576943166736',
    projectId: 'flutter-dartapp',
    storageBucket: 'flutter-dartapp.appspot.com',
    androidClientId:
        '576943166736-tvniocq83o5l4sei7pn316bgroc13cbn.apps.googleusercontent.com',
    iosClientId:
        '576943166736-26qb5j9psb4l8nmqd34n3aac69guun7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.dartApp',
  );
}
