// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFb7oChuknYWMD57rmaRzCMUpSN2ksj18',
    appId: '1:576943166736:android:12cde6fed90d4d916d0195',
    messagingSenderId: '576943166736',
    projectId: 'flutter-dartapp',
    databaseURL: 'https://flutter-dartapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-dartapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBretxFeAKmvQpM1b-uMAYonpOQqokWb5g',
    appId: '1:576943166736:ios:1ca2d71a754536856d0195',
    messagingSenderId: '576943166736',
    projectId: 'flutter-dartapp',
    databaseURL: 'https://flutter-dartapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-dartapp.appspot.com',
    androidClientId: '576943166736-tvniocq83o5l4sei7pn316bgroc13cbn.apps.googleusercontent.com',
    iosBundleId: 'com.darttrack',
  );
}
